name: inasistapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.4
  http: ^1.4.0
  gsheets: ^0.5.0
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_file: ^3.3.2
  share_plus: ^11.1.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
