<?php
header('Content-Type: application/json');
$materias = [
    "ARTISTICA 1101",
    "ARTISTICA 1102",
    "ARTISTICA 701",
    "EMPRENDIMIENTO 901",
    "EMPRENDIMIENTO Y PROYECTO 1101",
    "EMPRENDIMIENTO Y PROYECTO 1102",
    "TECNOLOGIA E INFORMATICA 1001",
    "TECNOLOGIA E INFORMATICA 1002",
    "TECNOLOGIA E INFORMATICA 1101",
    "TECNOLOGIA E INFORMATICA 1102",
    "TECNOLOGIA E INFORMATICA 901"
];
echo json_encode($materias);
?>