<?php
header('Content-Type: application/json');

// Ejemplo de lista de profesores

$profesores = [
    "AIDA MILENA RIVERA",
    "ANA MILENA FERNÁNDEZ BOLAÑOS",
    "ANA SOFIA CARDENAS PETUMA",
    "BLANCA NELLY MARÍN GIRALDO",
    "CARLOS ALBERTO AGUIRRE GONZÁLEZ",
    "CARLOS ARMANDO RÍOS ÁLVAREZ",
    "CARLOS ARTURO CUARTAS RAMIREZ",
    "CESAR LEANDRO PATIÑO VELEZ",
    "DANIEL QUICENO RIVERA",
    "DANNY DANIEL QUINTERO GIRALDO",
    "DELCID DE JESÚS BUENO ARANDIA",
    "DERLY JOANNA PUERTAS",
    "DIANA LISBETH VÁSQUEZ LONDOÑO",
    "DIANA MARCELA ROMERO GAMBOA",
    "FANNY ELENA MENA R",
    "GERMAN ALONSO CASTRILLÓN MARTÍNEZ",
    "GLORIA LILIANA QUINTERO OROZCO",
    "ILDORY JARAMILLO",
    "JAVIER DE JESÚS AGUDELO CARVAJAL",
    "JESÚS ALBERTO MEJÍA RÍOS",
    "JHON JAIRO VÉLEZ TEJADA",
    "JOHN EDWIN ARBOLEDA ACEVEDO",
    "JON JAMES VASCO RODRÍGUEZ",
    "MARÍA DEL CARMEN SANTA",
    "MARIA ELIZABETH GUERRERO R",
    "MARTA LIDA CASTAÑO OSORIO",
    "ONEIDA JARAMILLO OCAMPO",
    "PABLO REINOSO HENAO"
];

echo json_encode($profesores);
